os: linux
language: php
php:
  - 7.4

branches:
  only:
    - master

# Install Cecil and theme(s)
install:
  - |
    echo "Downloading Cecil..."
    if [[ -z "$CECIL_VERSION" ]]; then
      curl -sSOL https://cecil.app/cecil.phar
    else
      curl -sSOL https://cecil.app/download/$CECIL_VERSION/cecil.phar
    fi
  - php cecil.phar --version
  - |
    echo "Installing themes..."
    composer install --prefer-dist --no-dev --no-progress --no-interaction

# Run Cecil build
script:
  - php cecil.phar build -v

# Deploy to GitHub Pages
deploy:
  provider: pages
  edge: true
  token: $GH_TOKEN # set this env. variable in Travis CI settings
  local_dir: _site
  on:
    branch: master
