title: Static blog
baseline: Static blog for some things.
description: My blog powered by Cecil.
baseurl: /
canonicalurl: true
keywords: [Taboadaa, Static Site]
author: Adrien Taboada
date:
  format: j F Y
  timezone: Europe/Zurich
theme:
  - hyde
hyde:
  sidebar:
    sticky: true # Content to the bottom of the sidebar
  theme: '' # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: false # Reverse layout
pagination:
  max: 5
  path: 'page'
